### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by lafilnemi** [itaymigdal/LOLSpoof#2]
Trying to compile this on version 2.0.2 gives me a compiler error:

![image](https://github.com/itaymigdal/LOLSpoof/assets/1769976/7195eb5a-f5d1-4bf7-8d6e-9d111ecc9a11)

**Comment by itaymigdal** [comment]
Known issue. Compile with Nim 1.6 plz.
